### ISSUE TITLE
Make function naming consistent

### ISSUE THREAD

**Issue by freghar** [NouberNou/intercept#28]
Opening the "SQF->C++ Conversion Coverage statistics" issue and selecting the top-of-the-list completed function at this time, unary__get3denactionstate__string__ret__scalar, reveals what appear to be naming inconsistencies between the surrounding functions, ie.

get3deniconsvisible
is3denmultiplayer
get_3den_action_state
edit_3den_mission_attributes

(notice the `_' difference)

There are probably more such occurences, maybe making a note about function naming in some documentation file would be beneficial, possibly with argument / return value mapping between VR engine functions and the C++ API, so that ie. string is always returned as std::string and not as char* or std::stringstream.

Thanks.

**Comment by Glowbal** [comment]
Those are the pointers to the sqf functions. They use the sqf function name.

Example of an implementation using such a pointer: https://github.com/NouberNou/intercept/blob/master/src/client/intercept/client/sqf/config.cpp#L14-L19

We wrap those in a wrapper function that abstracts away the wierdness of sqf.

**Comment by Verox-** [comment]
All functions are to be in snake case, some functions were autogenerated accidentally without the underscores, all of which have been fixed in another branch (to be merged soon.)

Right now std::string is being used as a return (and param) type for all functions, floats are used to represent numbers, std::vectors represent single-type arrays and structs represent structured return data.

**Comment by jonpas** [comment]
This can be closed?
