### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by dbenson24** [NouberNou/intercept#8]
Could we start a Slack for this?
or a gitter

**Comment by NouberNou** [comment]
Currently there is a private Slack channel for this on ACE's public Slack. Right now I want to keep it limited to people that are contributing code directly to the project right now since it is still in somewhat of its infancy. When it gets closer to the first release getting a dedicated Slack will be more of a priority.

**Comment by dbenson24** [comment]
Okay, I just ask because I'd love to contribute to this project

**Comment by NouberNou** [comment]
If you want to contribute, right now simple wrappers are the biggest task. I'd suggest checking out the latest commits to master, specifically the wrappers already implemented in the [client\intercept\client\sqf folder](https://github.com/NouberNou/intercept/tree/master/src/client/intercept/client/sqf). Make a new ticket, and assign it to yourself (I think you should be able to do that?) and just put in a check list of which functions you are writing wrappers for and then make a PR.

Priority is on the simple ones. A really important set would be the display/controls commands.
